  var legendaryitems = [
    { name: "ザズ＝ザクのレルムスパイク", effect: "10秒ごとにゴールドを獲得\n体力、マナの回復量増加\n体力＋200", passive: "敵チャンピオンにダメージを与えると周囲の敵にダメージを与える。\n発動時ステルスワードを設置する。4個まで所持可能でショップに戻ると補充される",money:"ワールドアトラスから進化で入手", type: "legendary"},
    { name: "ブラッドソング", effect: "10秒ごとにゴールドを獲得\n体力、マナの回復量増加\n体力＋200", passive: "スキルを使用した次の通常攻撃が雇用化される。\n発動時ステルスワードを設置する。4個まで所持可能でショップに戻ると補充される",money:"ワールドアトラスから進化で入手", type: "legendary"},
    { name: "至点のソリ", effect: "10秒ごとにゴールドを獲得\n体力、マナの回復量増加\n体力＋200", passive: "敵チャンピオンに移動妨害を与えると自身と周囲の味方で一番体力が低いチャンピオンを回復し移動速度が増加する。\n発動時ステルスワードを設置する。4個まで所持可能でショップに戻ると補充される",money:"ワールドアトラスから進化で入手", type: "legendary"},
    { name: "ドリームメーカー", effect: "10秒ごとにゴールドを獲得\n体力、マナの回復量増加\n体力＋200", passive: "味方に体力回復、シールドを付与すると、味方は次に受ける攻撃を軽減し次の通常攻撃が強化される。\n発動時ステルスワードを設置する。4個まで所持可能でショップに戻ると補充される",money:"ワールドアトラスから進化で入手", type: "legendary"},
    { name: "セレスティアルオポジション", effect: "10秒ごとにゴールドを獲得\n体力、マナの回復量増加\n体力＋200", passive: "敵チャンピオンから受けるダメージを軽減する。その後周囲の敵に移動速度低下を与える。\n発動時ステルスワードを設置する。4個まで所持可能でショップに戻ると補充される",money:"ワールドアトラスから進化で入手", type: "legendary"},
    { name: "メジャイソウルスティーラー", effect: "魔力＋20\n体力＋100", passive: "敵のキルに関与すると魔力が増加する。自身が死亡するとスタックが減る",money:"1500G", type: "legendary"},
    { name: "ジークコンバージェンス", effect: "体力＋200\nマナ＋250\n物理防御＋30\nスキルヘイスト＋20", passive: "アルティメットスキルを使用すると自身の周囲に5秒間移動速度低下とダメージを与える嵐を発生させる。",money:"2200G", type: "legendary"},
    { name: "モレロノミコン", effect: "魔力＋90\nスキルヘイスト＋15", passive: "敵チャンピオンにダメージを与えると敵のあらゆる回復効果が低下する。",money:"2200G", type: "legendary"},
    { name: "シュレリアの戦歌", effect: "魔力＋55\nスキルヘイスト＋15\n移動速度＋8％\nマナの回復量増加", passive: "発動時周囲の味方の移動速度を増加させる。",money:"2200G", type: "legendary"},
    { name: "ヘリアの残響", effect: "魔力＋40\n体力＋200\nスキルヘイスト＋20\nマナの回復量が増加 ", passive: "敵にダメージを与え、味方に回復またはシールドを付与すると最も近くにいる敵チャンピオンにダメージを与える。",money:"2200G", type: "legendary"},
    { name: "ムーンストーンの再生", effect: "魔力＋30\n体力＋250\nスキルヘイスト＋20\nマナの回復量増加", passive: "味方への回復、シールド付与がもう1体へ連鎖する",money:"2200G", type: "legendary"},
    { name: "騎士の誓い", effect: "体力＋300\n物理防御＋45\nスキルヘイスト＋15", passive: "指定した味方が受けるダメージの一部を肩代わりし、指定した味方が与えたダメージの一部を体力として回復する。",money:"2200G", type: "legendary"},
    { name: "ソラリのロケット", effect: "体力＋200\n物理防御＋30\n魔法防御＋30\nスキルヘイスト＋10", passive: "発動時、周囲の味方にシールドを付与する。",money:"2200G", type: "legendary"},
    { name: "帝国の指令", effect: "効果1", passive: "",money:"2300G", type: "legendary"},
    { name: "アーデントセンサー", effect: "効果1", passive: "",money:"2300G", type: "legendary"},
    { name: "フローウォータースタッフ", effect: "効果1", passive: "",money:"2300G", type: "legendary"},
    { name: "リデンプション", effect: "効果1", passive: "",money:"2300G", type: "legendary"},
    { name: "ミカエルの祝福", effect: "効果1", passive: "",money:"2300G", type: "legendary"},
    { name: "ビジラントワードストーン", effect: "効果1", passive: "",money:"G", type: "legendary"},
    { name: "冬の訪れ", effect: "効果1", passive: "",money:"2400G", type: "legendary"},
    { name: "フローズンハート", effect: "効果1", passive: "",money:"2400G", type: "legendary"},
    { name: "アビサルマスク", effect: "効果1", passive: "",money:"2400G", type: "legendary"},
    { name: "ヘクステックロケットベルト", effect: "効果1", passive: "",money:"2500G", type: "legendary"},
    { name: "毒蛇の牙", effect: "効果1", passive: "",money:"2500G", type: "legendary"},
    { name: "アナセマチェイン", effect: "効果1", passive: "",money:"2500G", type: "legendary"},
    { name: "先人の道標", effect: "効果1", passive: "",money:"2500G", type: "legendary"},
    { name: "ロッドオブエイジス", effect: "効果1", passive: "",money:"2600G", type: "legendary"},
    { name: "リーライクリスタルセプター", effect: "効果1", passive: "",money:"2600G", type: "legendary"},
    { name: "アンブラルグレイブ", effect: "効果1", passive: "",money:"2600G", type: "legendary"},
    { name: "アイスボーンガントレット", effect: "効果1", passive: "",money:"2600G", type: "legendary"},
    { name: "ホライゾンフォーカス", effect: "効果1", passive: "",money:"2700G", type: "legendary"},
    { name: "ドーンコア", effect: "効果1", passive: "",money:"2700G", type: "legendary"},
    { name: "妖夢の霊剣", effect: "効果1", passive: "",money:"2700G", type: "legendary"},
    { name: "オポチュニティー", effect: "効果1", passive: "",money:"G", type: "legendary"},
    { name: "ソーンメイル", effect: "効果1", passive: "",money:"2700G", type: "legendary"},
    { name: "ランデュインオーメン", effect: "効果1", passive: "",money:"2700G", type: "legendary"},
    { name: "サンファイアイージス", effect: "効果1", passive: "",money:"2700G", type: "legendary"},
    { name: "マリグナンス", effect: "効果1", passive: "",money:"2800G", type: "legendary"},
    { name: "ナイトエッジ", effect: "効果1", passive: "",money:"2800G", type: "legendary"},
    { name: "ルナーンハリケーン", effect: "効果1", passive: "",money:"2800G", type: "legendary"},
    { name: "ファントムダンサー", effect: "効果1", passive: "",money:"2800G", type: "legendary"},
    { name: "ウィッツエンド", effect: "効果2", passive: "",money:"2800G", type: "legendary"},
    { name: "赤月の刃", effect: "効果3", passive: "",money:"2800G", type: "legendary"},
    { name: "マルモティウスの胃袋", effect: "効果3", passive: "",money:"2800G", type: "legendary"},
    { name: "ケミパンクチェーンソード", effect: "効果3", passive: "",money:"2800G", type: "legendary"},
    { name: "終わりなき絶望", effect: "効果3", passive: "",money:"2800G", type: "legendary"},
    { name: "自然の力", effect: "効果3", passive: "",money:"2800G", type: "legendary"},
    { name: "ホロウレディアンス", effect: "効果3", passive: "",money:"2800G", type: "legendary"},
    { name: "クリプトブルーム", effect: "効果2", passive: "",money:"2850G", type: "legendary"},
    { name: "マナムネ", effect: "効果3", passive: "",money:"2900G", type: "legendary"},
    { name: "ストームサージ", effect: "効果3", passive: "",money:"2900G", type: "legendary"},
    { name: "ボルテイクサイクロソード", effect: "効果3", passive: "",money:"2900G", type: "legendary"},
    { name: "エッセンスリーバー", effect: "効果3", passive: "",money:"2900G", type: "legendary"},
    { name: "スピリットビサージュ", effect: "効果3", passive: "",money:"2900G", type: "legendary"},
    { name: "ケイニックルーケルン", effect: "効果3", passive: "",money:"2900G", type: "legendary"},
    { name: "デッドマンプレート", effect: "効果2", passive: "",money:"2900G", type: "legendary"},
    { name: "ルーデンコンパニオン", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "アークエンジェルスタッフ", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "ナッシャートゥース", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "ライアンドリーの仮面", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "コズミックドライブ", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "ヴォイドスタッフ", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "グインソーレイジブレード", effect: "効果2", passive: "",money:"3000G", type: "legendary"},
    { name: "ヒュブリス", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "アクシオムアーク", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "クラーケンスレイヤー", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "スタティックシヴ", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "ラピッドファイアキャノン", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "イモータルシールドボウ", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "マーキュリアルシミター", effect: "効果2", passive: "",money:"3000G", type: "legendary"},
    { name: "ドミニクリガード", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "モータルリマインダー", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "ストライドブレイカー", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "テルミヌス", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "実験的へクスプレート", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "ハルブレイカー", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "ブラッククリーバー", effect: "効果2", passive: "",money:"3000G", type: "legendary"},
    { name: "心の鋼", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "ステラックの篭手", effect: "効果3", passive: "",money:"3000G", type: "legendary"},
    { name: "バンシーヴェール", effect: "効果3", passive: "",money:"3100G", type: "legendary"},
    { name: "リッチヴェイン", effect: "効果3", passive: "",money:"3100G", type: "legendary"},
    { name: "リフトメーカー", effect: "効果3", passive: "",money:"3100G", type: "legendary"},
    { name: "コレクター", effect: "効果3", passive: "",money:"3100G", type: "legendary"},
    { name: "ストームレイザー", effect: "効果2", passive: "",money:"3100G", type: "legendary"},
    { name: "ショウジンの矛", effect: "効果3", passive: "",money:"3100G", type: "legendary"},
    { name: "サンダードスカイ", effect: "効果3", passive: "",money:"3100G", type: "legendary"},
    { name: "ワーモグアーマー", effect: "効果3", passive: "",money:"3100G", type: "legendary"},
    { name: "シャドウフレイム", effect: "効果3", passive: "",money:"3200G", type: "legendary"},
    { name: "セリルダの怨恨", effect: "効果3", passive: "",money:"3200G", type: "legendary"},
    { name: "ルインドキングブレード", effect: "効果3", passive: "",money:"3200G", type: "legendary"},
    { name: "デスダンス", effect: "効果2", passive: "",money:"3200G", type: "legendary"},
    { name: "ガーディアンエンジェル", effect: "効果3", passive: "",money:"3200G", type: "legendary"},
    { name: "変幻自在のジャック＝ショー", effect: "効果3", passive: "",money:"3200G", type: "legendary"},
    { name: "ゾーニャの砂時計", effect: "効果3", passive: "",money:"3300G", type: "legendary"},
    { name: "プロフェインハイドラ", effect: "効果3", passive: "",money:"3300G", type: "legendary"},
    { name: "インフィニティエッジ", effect: "効果3", passive: "",money:"3300G", type: "legendary"},
    { name: "ナヴォリクイックブレード", effect: "効果3", passive: "",money:"3300G", type: "legendary"},
    { name: "ラヴァナスハイドラ", effect: "効果2", passive: "",money:"3300G", type: "legendary"},
    { name: "タイタンハイドラ", effect: "効果3", passive: "",money:"3300G", type: "legendary"},
    { name: "トリニティフォース", effect: "効果3", passive: "",money:"3333G", type: "legendary"},
    { name: "ブラッドサースター", effect: "効果3", passive: "",money:"3400G", type: "legendary"},
    { name: "ラバドンデスキャップ", effect: "効果3", passive: "",money:"3600G", type: "legendary"}
  ];
  
  var epicitems = [
    { name: "リカーブボウ", effect: "攻撃速度＋15%", passive: "通常攻撃で追加ダメージを15を与える。" ,money:"700G", type: "epic"},
    { name: "キルヒアイスシャード", effect: "攻撃力＋15", passive: "移動と通常攻撃たまるスタックが最大の次の通常攻撃に追加ダメージ" ,money:"700G", type: "epic"},
    { name: "忘却のオーブ", effect: "魔力＋30", passive: "敵チャンピオンにダメージを与えると相手のすべての回復効果が低下する。" ,money:"800G", type: "epic"},
    { name: "フォビドゥンアイドル", effect: "マナの自動回復が増加\n回復とシールド量が増加", passive: "" ,money:"800G", type: "epic"},
    { name: "エクスキューショナーコーリング", effect: "攻撃力＋15", passive: "敵チャンピオンにダメージを与えると相手のすべての回復効果が低下する。" ,money:"800G", type: "epic"},
    { name: "キンドルジェム", effect: "体力＋200\nスキルヘイスト＋10", passive: "" ,money:"800G", type: "epic"},
    { name: "チェインベスト", effect: "物理防御＋40", passive: "" ,money:"800G", type: "epic"},
    { name: "ブランブルベスト", effect: "物理防御＋30", passive: "通常攻撃を受けると攻撃してきた相手に6ダメージを与える。\n敵チャンピオンが攻撃した場合相手の回復効果が低下する。" ,money:"800G", type: "epic"},
    { name: "クリスタルブレーザー", effect: "体力＋200\n自動体力回復量が増加", passive: "" ,money:"800G", type: "epic"},
    { name: "翼のムーンプレート", effect: "体力＋150\n移動速度＋5％", passive: "" ,money:"800G", type: "epic"},
    { name: "エーテルウィスプ", effect: "魔力＋30\n移動速度＋5％", passive: "" ,money:"850G", type: "epic"},
    { name: "グレイシャルバックラー", effect: "物理防御＋20\nマナ＋250\nスキルヘイスト＋10", passive: "" ,money:"900G", type: "epic"},
    { name: "フィンディッシュの古書", effect: "魔力＋35\nスキルヘイスト＋10", passive: "" ,money:"900G", type: "epic"},
    { name: "レクトリクス", effect: "攻撃力＋20\n移動速度＋5％", passive: "" ,money:"900G", type: "epic"},
    { name: "ヴァンパイアセプター", effect: "攻撃力＋15\n　ライフスティール＋7%", passive: "" ,money:"900G", type: "epic"},
    { name: "ネガトロンクローク", effect: "魔法防御＋50", passive: "" ,money:"900G", type: "epic"},
    { name: "ジャイアントベルト", effect: "体力＋350", passive: "" ,money:"900G", type: "epic"},
    { name: "バンドルグラスの鏡", effect: "魔力＋20\nマナ自動回復増加\nスキルヘイスト＋10", passive: "" ,money:"1000G", type: "epic"},
    { name: "セレイテッドダーク", effect: "攻撃力＋25", passive: "脅威が10増加する" ,money:"1000G", type: "epic"},
    { name: "シーン", effect: "スキルヘイスト＋10", passive: "スキル使用後の次の通常攻撃が強化される。" ,money:"1000G", type: "epic"},
    { name: "ワーデンメイル", effect: "物理防御＋40", passive: "通常攻撃で受けるダメージを軽減する。" ,money:"1000G", type: "epic"},
    { name: "バミシンダー", effect: "体力＋300", passive: "周囲の敵に毎秒ダメージを与える。" ,money:"1000G", type: "epic"},
    { name: "ヘクステックオルタネーター", effect: "魔力＋50", passive: "敵にダメージを与えると追加でダメージを与える。" ,money:"1100G", type: "epic"},
    { name: "枯死の宝石", effect: "魔力＋25\n魔法防御貫通＋13％", passive: "" ,money:"1100G", type: "epic"},
    { name: "ジール", effect: "攻撃速度＋15%\nクリティカル率＋15%\n移動速度＋5％", passive: "" ,money:"1100G", type: "epic"},
    { name: "コールフィールドウォーハンマー", effect: "攻撃力＋25\nスキルヘイスト＋10", passive: "" ,money:"1100G", type: "epic"},
    { name: "スチールシジル", effect: "攻撃力＋15\n物理防御＋30", passive: "" ,money:"1100G", type: "epic"},
    { name: "トンネル堀り", effect: "攻撃力＋15\n体力＋250", passive: "" ,money:"1100G", type: "epic"},
    { name: "ファージ", effect: "攻撃力＋15\n体力＋200", passive: "通常攻撃を行うと2秒間移動速度が増加する。" ,money:"1100G", type: "epic"},
    { name: "ウォッチフルワードストーン", effect: "体力＋150\nスキルヘイスト＋10\n物理防御＋10\n魔法防御＋15", passive: "コントロールワードを3つまで持つことができる" ,money:"1100G", type: "epic"},
    { name: "ロストチャプター", effect: "魔力＋40\nマナ＋300\nスキルヘイスト＋10", passive: "レベルアップ時マナを回復する" ,money:"1200G", type: "epic"},
    { name: "ハースバウンドアックス", effect: "攻撃力＋20\n攻撃速度＋25%", passive: "" ,money:"1200G", type: "epic"},
    { name: "ティアマト", effect: "攻撃力＋20", passive: "通常攻撃が周囲の敵にダメージを与えるようになる。\n発動時自身の周囲にダメージを与える。" ,money:"1200G", type: "epic"},
    { name: "スペクターカウル", effect: "体力＋250\n魔法防御＋25", passive: "敵チャンピオンからダメージを受けると10秒間体力の自動回復が増加する。" ,money:"1250G", type: "epic"},
    { name: "久遠のカタリスト", effect: "体力＋350\nマナ＋300", passive: "敵チャンピオンからダメージを受けるとマナが回復する。消費したマナの一部を体力として回復する。" ,money:"1300G", type: "epic"},
    { name: "悲愴な仮面", effect: "魔力＋35", passive: "敵チャンピオンと戦闘時毎秒ダメージを当たる" ,money:"1300G", type: "epic"},
    { name: "ヌーンクィヴァー", effect: "攻撃力＋30\n攻撃速度＋15%", passive: "通常攻撃がミニオンとモンスターに追加ダメージを与える。" ,money:"1300G", type: "epic"},
    { name: "へクスドリンカー", effect: "攻撃力＋25\n魔法防御＋35", passive: "魔法ダメージを受けて体力が低くなると魔法ダメージを防ぐシールドを獲得する。" ,money:"1300G", type: "epic"},
    { name: "クイックシルバーサッシュ", effect: "魔法防御＋30", passive: "発動時現在受けている行動妨害を除去する（ノックアップは防げない）" ,money:"1300G", type: "epic"},
    { name: "ブルータライザー", effect: "攻撃力＋25\nスキルヘイスト＋10\n脅威＋8", passive: "" ,money:"1337G", type: "epic"},
    { name: "ラストウィスパー", effect: "攻撃力＋20\n物理防御貫通＋18％", passive: "" ,money:"1450G", type: "epic"},
    { name: "シーカーアームガード", effect: "魔力＋45\n物理防御＋25", passive: "発動時2.5秒間何も行動できないが敵からダメージも何も受けなくなる。" ,money:"1600G", type: "epic"},
    { name: "ヴァ―ダントバリア", effect: "魔力＋40\n魔法防御＋30", passive: "次に敵から受けるスキルをブロックするシールドを獲得する。" ,money:"1800G", type: "epic"},
  ];
  
  var basicitems = [
    { name: "輝きのモート", effect: "スキルヘイスト＋5", passive: "" ,money:"250G", type: "basic"},
    { name: "フェアリーチャーム", effect: "マナの自動回復が増加", passive: "" ,money:"250G", type: "basic"},
    { name: "ダガー", effect: "攻撃速度＋12％", passive: "" ,money:"300G", type: "basic"},
    { name: "クロースアーマー", effect: "物理防御＋15", passive: "" ,money:"300G", type: "basic"},
    { name: "再生の珠", effect: "体力の自動回復が増加", passive: "" ,money:"300G", type: "basic"},
    { name: "サファイアクリスタル", effect: "マナ＋250", passive: "" ,money:"350G", type: "basic"},
    { name: "ロングソード", effect: "攻撃力＋10", passive: "" ,money:"350G", type: "basic"},
    { name: "ルビークリスタル", effect: "体力＋150", passive: "" ,money:"400G", type: "basic"},
    { name: "増魔の書", effect: "魔力＋20", passive: "" ,money:"400G", type: "basic"},
    { name: "ヌルマジックマント", effect: "魔法防御＋25", passive: "" ,money:"450G", type: "basic"},
    { name: "アジリティクローク", effect: "クリティカル率＋15%", passive: "" ,money:"600G", type: "basic"},
    { name: "ブラスティックワンド", effect: "魔力＋45", passive: "" ,money:"850G", type: "basic"},
    { name: "ピッケル", effect: "攻撃力＋25", passive: "" ,money:"875G", type: "basic"},
    { name: "ムダニデカイロッド", effect: "魔力＋70", passive: "" ,money:"1250G", type: "basic"},
    { name: "B.F.ソード", effect: "攻撃力＋40", passive: "" ,money:"1300G", type: "basic"},
  ];
  
  var starteritems = [
    { name: "ダークシール", effect: "魔力＋15\n体力＋50", passive: "敵のキルに関与すると魔力が増加する。自身が死亡すると増加した魔力の一部を失う" ,money:"350G", type: "starter"},
    { name: "女神の涙", effect: "マナ＋240", passive: "敵にスキルを当てるとマナが増加する。\n通常攻撃がミニオンに対して追加ダメージを与える。" ,money:"400G", type: "starter"},
    { name: "ドランリング", effect: "魔力＋18\n体力＋90", passive: "毎秒マナが回復する。\n通常攻撃がミニオンに対して追加ダメージを与える。" ,money:"450G", type: "starter"},
    { name: "ドランブレード", effect: "攻撃力＋10\n体力＋100\nライフスティール＋3.5％", passive: "" ,money:"450G", type: "starter"},
    { name: "カル", effect: "攻撃力＋7", passive: "通常攻撃が当たるたび体力が少しだけ回復する。\nミニオンを倒すと追加でお金を貰える。" ,money:"450G", type: "starter"},
    { name: "ドランシールド", effect: "体力＋110", passive: "5秒ごとに体力が自動で少し回復する。\n通常攻撃がミニオンに倒して追加ダメージを与える。" ,money:"450G", type: "starter"},
    { name: "スコーチクロウの幼体", effect: "スコーチクロウを召喚してジャングルで支援させる", passive: "40体のジャングルのモンスターを倒すと敵に与える通常攻撃またはスキルに移動速度低下とダメージを与える。" ,money:"450G", type: "starter"},
    { name: "ガストウォーカーの幼体", effect: "ガストウォーカーを召喚してジャングルで支援させる", passive: "40体のジャングルのモンスターを倒すと自身が茂みに入ると移動速度が増加する。" ,money:"450G", type: "starter"},
    { name: "モスストンパーの幼体", effect: "モスストンバーを召喚してジャングルで支援させる", passive: "40体のジャングルのモンスターを倒すと非戦闘時にシールドを獲得する。" ,money:"450G", type: "starter"},
    { name: "ワールドアトラス", effect: "10秒ごとに＋3ゴールド\n体力、マナ自動回復が増加する。", passive: "18秒ごとに敵にダメージを与えるかミニオンを倒すと最も近くの味方とゴールドを共有する。\n500ゴールド獲得するとこのアイテムが進化する。" ,money:"400G", type: "starter"},
    
  ];

  var bootsitems = [
  { name: "ちょっと魔法のかかった靴", effect: "追加で移動速度を+10する", money:"時間経過で獲得", type: "boots"},
  { name: "ブーツ", effect: "移動速度+25", money:"300G", type: "boots"},
  { name: "スイフトネスブーツ", effect: "移動速度+60 スロウ効果を25％減少する", money:"900G", type: "boots"},
  { name: "アイオニアブーツ", effect: "移動速度+45スキルヘイスト+20", money:"950G", type: "boots"},
  { name: "モビリティブーツ", effect: "移動速度+25\n(非戦闘状態で5秒間いると移動速度が115に増加)", money:"G", type: "boots"},
  { name: "バーサーカーブーツ", effect: "移動速度+45 攻撃速度+35％", money:"1100G", type: "boots"},
  { name: "ソーサラーブーツ", effect: "移動速度+45 魔法防御貫通+18", money:"1100G", type: "boots"},
  { name: "プレートスチールキャップ", effect: "移動速度+45 物理防御+20", money:"1100G", type: "boots"},
  { name: "マーキュリーブーツ", effect: "移動速度+45 魔法防御+25 行動妨害耐性+30%", money:"1100G", type: "boots"},
];

var portionitems = [
{ name: "体力ポーション", effect: "15秒かけて体力を120回復する",money:"50G", type: "portion"},
{ name: "詰め替えポーション", effect: "1チャージを消費して体力を100回復する。2チャージ保持していてショップを訪れるとチャージが回復する。",money:"150G", type: "portion"},
{ name: "コラプトポーション", effect: "1チャージを消費して体力100とマナ75を12秒かけて回復する。さらに、12秒の間にAAと攻撃系スキルで敵に火をつけ15（マナを獲得できなかった場合20）の魔法ダメージを与える",money:"500G", type: "portion"},
];

var Worditems = [
{ name: "ステルスワード", effect: "味方に視界を与える。\nまた敵からはインビジブル状態となる。",money:"無料", type: "Word"},
{ name: "コントロールワード", effect: "味方に視界を与える。\nこの周辺にあるインビジブルの罠、カモフラージュの敵を可視化し、敵のステルスワードを可視化＆無効化する。",money:"75G", type: "Word"},
{ name: "オラクルレンズ", effect: "自分の周りをスキャンし範囲内の敵を見ることができる。敵の罠を可視化して一時敵に敵のステルスワードも可視化＆無効化する。",money:"無料", type: "Word"},
{ name: "フォーサイトオルタレーション", effect: "離れた位置に壊れやすい可視状態のワードを設置する。",money:"無料", type: "Word"},
];
